
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.redbee.visa;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-13T12:58:07.788-03:00
 * Generated source version: 2.7.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "LiquidacionWSServiceService",
                      portName = "liquidacionesWSPort",
                      targetNamespace = "http://erad.visa.com/",
                      wsdlLocation = "/tmp/tempdir2504496070561278002.tmp/liquidacionWS_1.wsdl",
                      endpointInterface = "com.redbee.visa.LiquidacionesWS")
                      
public class LiquidacionesWSImpl implements LiquidacionesWS {

    private static final Logger LOG = Logger.getLogger(LiquidacionesWSImpl.class.getName());

    /* (non-Javadoc)
     * @see com.redbee.visa.LiquidacionesWS#getLiquidacion(java.lang.String  liquidacionID )*
     */
    public com.redbee.visa.LiquidacionResponse getLiquidacion(java.lang.String liquidacionID) { 
        LOG.info("Executing operation getLiquidacion");
        System.out.println(liquidacionID);
        try {
            com.redbee.visa.LiquidacionResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.redbee.visa.LiquidacionesWS#getGrailsApplication(*
     */
    public java.lang.Object getGrailsApplication() { 
        LOG.info("Executing operation getGrailsApplication");
        try {
            java.lang.Object _return = new java.lang.Object();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.redbee.visa.LiquidacionesWS#setGrailsApplication(java.lang.Object  arg0 )*
     */
    public void setGrailsApplication(java.lang.Object arg0) { 
        LOG.info("Executing operation setGrailsApplication");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.redbee.visa.LiquidacionesWS#setRepositoryService(java.lang.Object  arg0 )*
     */
    public void setRepositoryService(java.lang.Object arg0) { 
        LOG.info("Executing operation setRepositoryService");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.redbee.visa.LiquidacionesWS#getRepositoryService(*
     */
    public java.lang.Object getRepositoryService() { 
        LOG.info("Executing operation getRepositoryService");
        try {
            java.lang.Object _return = new java.lang.Object();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.redbee.visa.LiquidacionesWS#getLiquidaciones(java.lang.String  fechaDesde ,)java.lang.String  fechaHasta ,)java.lang.String  numeroCuenta ,)java.lang.String  plataforma )*
     */
    public com.redbee.visa.LiquidacionesResponse getLiquidaciones(java.lang.String fechaDesde,java.lang.String fechaHasta,java.lang.String numeroCuenta,java.lang.String plataforma) { 
        LOG.info("Executing operation getLiquidaciones");
        System.out.println(fechaDesde);
        System.out.println(fechaHasta);
        System.out.println(numeroCuenta);
        System.out.println(plataforma);
        try {
            com.redbee.visa.LiquidacionesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
