package com.redbee.visa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-13T12:58:07.806-03:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://erad.visa.com/", name = "liquidacionesWS")
@XmlSeeAlso({ObjectFactory.class})
public interface LiquidacionesWS {

    @WebResult(name = "liquidacionResponse", targetNamespace = "")
    @RequestWrapper(localName = "getLiquidacion", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetLiquidacion")
    @WebMethod(action = "http://erad.visa.com/getLiquidacion")
    @ResponseWrapper(localName = "getLiquidacionResponse", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetLiquidacionResponse")
    public com.redbee.visa.LiquidacionResponse getLiquidacion(
        @WebParam(name = "liquidacionID", targetNamespace = "")
        java.lang.String liquidacionID
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getGrailsApplication", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetGrailsApplication")
    @WebMethod
    @ResponseWrapper(localName = "getGrailsApplicationResponse", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetGrailsApplicationResponse")
    public java.lang.Object getGrailsApplication();

    @RequestWrapper(localName = "setGrailsApplication", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.SetGrailsApplication")
    @WebMethod
    @ResponseWrapper(localName = "setGrailsApplicationResponse", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.SetGrailsApplicationResponse")
    public void setGrailsApplication(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Object arg0
    );

    @RequestWrapper(localName = "setRepositoryService", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.SetRepositoryService")
    @WebMethod
    @ResponseWrapper(localName = "setRepositoryServiceResponse", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.SetRepositoryServiceResponse")
    public void setRepositoryService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Object arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRepositoryService", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetRepositoryService")
    @WebMethod
    @ResponseWrapper(localName = "getRepositoryServiceResponse", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetRepositoryServiceResponse")
    public java.lang.Object getRepositoryService();

    @WebResult(name = "liquidacionesResponse", targetNamespace = "")
    @RequestWrapper(localName = "getLiquidaciones", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetLiquidaciones")
    @WebMethod(action = "http://erad.visa.com/getLiquidaciones")
    @ResponseWrapper(localName = "getLiquidacionesResponse", targetNamespace = "http://erad.visa.com/", className = "com.redbee.visa.GetLiquidacionesResponse")
    public com.redbee.visa.LiquidacionesResponse getLiquidaciones(
        @WebParam(name = "fechaDesde", targetNamespace = "")
        java.lang.String fechaDesde,
        @WebParam(name = "fechaHasta", targetNamespace = "")
        java.lang.String fechaHasta,
        @WebParam(name = "numeroCuenta", targetNamespace = "")
        java.lang.String numeroCuenta,
        @WebParam(name = "plataforma", targetNamespace = "")
        java.lang.String plataforma
    );
}
