
package client.com.redbee.visa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.interceptor.LoggingInInterceptor;
import org.apache.cxf.interceptor.LoggingOutInterceptor;
import org.apache.cxf.sts.token.provider.SamlCallbackHandler;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-13T12:51:44.099-03:00
 * Generated source version: 2.7.16
 * 
 */
public final class LiquidacionesWS_LiquidacionesWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://erad.visa.com/", "LiquidacionWSServiceService");
    //private static final QName SERVICE_NAME = new QName("http://apache.org/hello_world_soap_http", "SOAPService");
    private static final QName PORT_NAME = new QName("http://erad.visa.com/", "liquidacionesWSPort");
    
    private LiquidacionesWS_LiquidacionesWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {

        URL wsdlURL = new URL("http://localhost:8080/resumenes/services/liquidacionWS?wsdl");
        LiquidacionWSServiceService ss = new LiquidacionWSServiceService(wsdlURL, SERVICE_NAME);
        LiquidacionesWS port = ss.getLiquidacionesWSPort(); 
        
        Client client = ClientProxy.getClient(port);
        client.getInInterceptors().add(new LoggingInInterceptor());
        client.getOutInterceptors().add(new LoggingOutInterceptor()); 
        try {
        	
        	
        	
            ((BindingProvider)port).getRequestContext().put("ws-security.signature.username", "007");
        ((BindingProvider)port).getRequestContext().put("ws-security.encryption.username", "prismakey");
        ((BindingProvider)port).getRequestContext().put("ws-security.callback-handler", "client.com.redbee.visa.ClientKeystorePasswordCallback");
        ((BindingProvider)port).getRequestContext().put("ws-security.saml-callback-handler", new SamlCallbackHandler());
        //((BindingProvider)port).getRequestContext().put("ws-security.encryption.properties", "/ws-secpol-wsdl/service.properties");
        ((BindingProvider)port).getRequestContext().put("ws-security.signature.properties", "clientKeystore.properties");
			//        	 System.out.println("Invoking getLiquidacion...");
			//             java.lang.String _getLiquidacion_liquidacionID = "CRE-PPL05179278612015-04-09 00:00:00.0";
			//             client.com.redbee.visa.LiquidacionResponse _getLiquidacion__return = port.getLiquidacion(_getLiquidacion_liquidacionID);
			//             System.out.println("getLiquidacion.result=" + _getLiquidacion__return);
        	System.out.println("Invoking getLiquidaciones...");
            java.lang.String _getLiquidaciones_fechaDesde = "01/01/2014";
            java.lang.String _getLiquidaciones_fechaHasta = "31/12/2015";
            java.lang.String _getLiquidaciones_numeroCuenta = "0122082306";
            java.lang.String _getLiquidaciones_plataforma = "CRE-PPL";
            
            
            
            
            
            
            client.com.redbee.visa.LiquidacionesResponse _getLiquidaciones__return = port.getLiquidaciones(_getLiquidaciones_fechaDesde, _getLiquidaciones_fechaHasta, _getLiquidaciones_numeroCuenta, _getLiquidaciones_plataforma);
            System.out.println("getLiquidaciones.result=" + _getLiquidaciones__return);
        } catch (Exception e) {
            System.out.println("Invocation failed with the following: " + e.getCause());
            System.out.println();
        }

        System.exit(0);
    }

    
  
}
