package client.com.redbee.visa;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-13T12:58:07.815-03:00
 * Generated source version: 2.7.16
 * 
 */
@WebServiceClient(name = "LiquidacionWSServiceService", 
                  wsdlLocation = "/home/pcastelo/Downloads/wsdl.xml",
                  targetNamespace = "http://erad.visa.com/") 
public class LiquidacionWSServiceService extends Service {

 

    public final static QName SERVICE = new QName("http://erad.visa.com/", "LiquidacionWSServiceService");
    public final static QName LiquidacionesWSPort = new QName("http://erad.visa.com/", "liquidacionesWSPort");

    public LiquidacionWSServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LiquidacionWSServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

  
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LiquidacionWSServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LiquidacionWSServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LiquidacionesWS
     */
    @WebEndpoint(name = "liquidacionesWSPort")
    public LiquidacionesWS getLiquidacionesWSPort() {
        return super.getPort(LiquidacionesWSPort, LiquidacionesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LiquidacionesWS
     */
    @WebEndpoint(name = "liquidacionesWSPort")
    public LiquidacionesWS getLiquidacionesWSPort(WebServiceFeature... features) {
        return super.getPort(LiquidacionesWSPort, LiquidacionesWS.class, features);
    }

}
